const assert = require('node:assert/strict');
const api = require('../shared/player-levels.js');
const now = '2026-09-07T09:00:00.000Z';
const input = {selfLevel:'N', answers:Array(6).fill('ทำได้บางครั้ง'), experience:'เริ่มฝึก'};
const initial = api.updateSelf({}, input, 'user', now);
assert.equal(api.status({assessment:initial}), 'รอผู้จัดตรวจระดับ');
assert.equal(api.effective({assessment:api.updateSelf({}, {...input,selfLevel:''}, 'user', now)}), '');
assert.throws(()=>api.updateSelf({}, {...input,answers:[]}, 'user', now));
assert.throws(()=>api.updateSelf({}, {...input,selfLevel:'fake'}, 'user', now));
const evidence = {decision:'confirm',level:'P',assessor:'ผู้จัด ก',qualification:'ผู้จัดก๊วน',observedDate:'2026-09-06',games:2,observations:Array(6).fill('ทำได้สม่ำเสมอ'),reason:'สังเกตตำแหน่งและการควบคุมลูกสองเกม',evidence:'รอบเย็น เปลี่ยนคู่เล่นระหว่างเกม'};
const approved = api.review(initial, evidence, 'admin', now);
assert.equal(api.confirmed({assessment:approved}), 'P');
const changed = api.updateSelf(approved, input, 'user', now);
assert.equal(changed.confirmedLevel, 'P');
assert.equal(changed.reviewedAt, approved.reviewedAt);
assert.equal(api.effective({assessment:changed}), 'P');
assert.ok(changed.events.length > approved.events.length);
const request = api.requestReview(changed, 'ฝีมือเปลี่ยน ขอให้ตรวจใหม่', 'user', now);
assert.equal(api.effective({assessment:request}), 'P');
assert.match(api.status({assessment:request}), /ใช้ระดับเดิม/);
assert.throws(()=>api.requestReview(request, 'ส่งซ้ำ', 'user', now));
const deferred = api.review(request, {decision:'defer',assessor:'ผู้จัด ก',reason:'ขอสังเกตเพิ่ม'}, 'admin', now);
assert.equal(deferred.confirmedLevel, 'P');
assert.equal(deferred.request.status, 'needs-evidence');
assert.throws(()=>api.review(request, {...evidence,games:1}, 'admin', now));
assert.throws(()=>api.review(request, {...evidence,observedDate:'2026-09-08'}, 'admin', now));
assert.throws(()=>api.review(request, {...evidence,observations:Array(6).fill('ไม่แน่ใจ')}, 'admin', now));
assert.throws(()=>api.review(request, {...evidence,level:'A/Pro',evidence:''}, 'admin', now));
assert.throws(()=>api.review(request, {...evidence,disputed:true,secondAssessor:'ผู้จัด ข',secondLevel:'C'}, 'admin', now));
assert.throws(()=>api.review(request, {...evidence,disputed:true,secondAssessor:'ผู้จัด ก',secondLevel:'P'}, 'admin', now));
const second = api.review(request, {...evidence,disputed:true,secondAssessor:'ผู้จัด ข',secondLevel:'P'}, 'admin', now);
assert.equal(second.request.status, 'resolved');
assert.equal(second.events.at(-1).previousLevel, 'P');
const legacy = {version:2,confirmedLevel:'C',history:[{selfLevel:'P'}]};
assert.deepEqual(api.updateSelf(legacy,input,'user',now).history, legacy.history);
console.log('PASS: initial/unknown, invalid input, retained confirmation, request/defer/resolve, duplicate request, evidence, disputed opinions, legacy history');
