const assert=require('node:assert/strict');
Object.defineProperty(global,'navigator',{value:{},configurable:true});
const memory=new Map();global.localStorage={getItem:k=>memory.has(k)?memory.get(k):null,setItem:(k,v)=>memory.set(k,v)};
require('../shared/player-levels.js');const R=require('../shared/service-rules.js');
const u={id:'test-user',role:'user'},admin={id:'test-admin',role:'admin'};
const login=s=>localStorage.setItem('smashup_session_v1',JSON.stringify(s));
const tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+1);const date=R.localDate(tomorrow);
const base={date,time:'17:00',court:'A',name:'ทดสอบ',phone:'081-234-5678'};
(async()=>{
 login(u);const r=await R.bookCourt(base,u);assert.equal(r.ownerId,u.id);
 await assert.rejects(R.bookCourt(base,u),/เพิ่งถูกจอง/);
 await assert.rejects(R.bookCourt({...base,court:'12'},u));
 await assert.rejects(R.bookCourt({...base,date:'2020-01-01'},u));
 await assert.rejects(R.bookCourt({...base,phone:'abc'},u));
 login({id:'other',role:'user'});await assert.rejects(R.cancel('court',r.id,u),/บัญชีเปลี่ยน/);await assert.rejects(R.cancel('court',r.id,{id:'other',role:'user'}),/เฉพาะรายการ/);
 login(u);await R.cancel('court',r.id,u);assert.equal(R.list(R.keys.court)[0].status,'ยกเลิกแล้ว');const renewed=await R.bookCourt(base,u);assert(renewed.id!==r.id);
 const list=R.list(R.keys.court);list.find(x=>x.id===renewed.id).paymentDueAt=new Date(Date.now()-1000).toISOString();R.write(R.keys.court,list);assert.equal(R.list(R.keys.court).find(x=>x.id===renewed.id).status,'ยกเลิกแล้ว');
 login(admin);await assert.rejects(R.setStatus('court',renewed.id,'ยืนยันแล้ว',admin),/หมดเวลา/);
 login(u);R.write('smashup_users_v1',[{...u,profile:{assessment:{version:2,selfLevel:'N',confirmedLevel:'P'}}}]);
 const b=await R.bookBuffet({date,session:'17:00–20:00',name:'ทดสอบ',phone:'0812345678',level:'N',shuttle:'0'},u);assert.equal(b.level,'P');assert.equal(b.levelSource,'organizer-confirmed');
 await assert.rejects(R.bookBuffet({date,session:'19:00–22:00',name:'ทดสอบ',phone:'0812345678',shuttle:'0'},u),/ทับซ้อน/);
 await R.cancel('buffet',b.id,u);assert.equal(R.list(R.keys.buffet)[0].status,'ยกเลิกแล้ว');
 const shop={service:'ลงชื่อซื้อของ',name:'ทดสอบ',phone:'0812345678',item:'ลูกแบดมินตัน',quantity:'0'};
 await assert.rejects(R.requestService(shop,u));await assert.rejects(R.requestService({...shop,quantity:'1.5'},u));
 const item=await R.requestService({...shop,quantity:'2'},u);await assert.rejects(R.requestService({...shop,quantity:'2'},u),/เดียวกัน/);
 await assert.rejects(R.requestService({service:'สมัครแข่งขัน',event:'SMASHUP CHAMPIONSHIP #1',category:'คู่ผสม',name:'ทดสอบ',phone:'0812345678'},u),/ชื่อคู่เล่น/);
 await assert.rejects(R.setStatus('service',item.id,'ดำเนินการแล้ว',u),/เฉพาะผู้ดูแล/);
 login(admin);await R.setStatus('service',item.id,'ดำเนินการแล้ว',admin);login(u);await assert.rejects(R.cancel('service',item.id,u),/ยกเลิกไม่ได้/);
 const raw=localStorage.getItem(R.keys.service);localStorage.setItem(R.keys.service,'broken');await assert.rejects(R.requestService({...shop,quantity:'1'},u),/เสียรูปแบบ/);assert.equal(localStorage.getItem(R.keys.service),'broken');localStorage.setItem(R.keys.service,raw);
 console.log('PASS: court conflicts, invalid dates/phone, fresh identity/ownership, cancel/rebook/expiry, confirmed level, overlapping buffet, service validation/duplicates, terminal states, malformed data retained');
})().catch(e=>{console.error(e);process.exit(1)});
