import type { BuffetBooking, BuffetStatus, CreateBuffetBookingInput } from '../../domain/entities/buffet'
import type { BuffetRepository } from '../../domain/repositories/buffet-repository'

interface BuffetRow { id: string; user_id: string; name: string; phone: string; date: string; session: string; level: string; level_source: string; note: string; shuttle: number; amount: number; group: string; status: string; payment_status: string; queue_number: number | null; created_at: string; updated_at: string }
function toBooking(row: BuffetRow): BuffetBooking { return { id: row.id, userId: row.user_id, name: row.name, phone: row.phone, date: row.date, session: row.session, level: row.level, levelSource: row.level_source, note: row.note, shuttle: row.shuttle, amount: row.amount, group: row.group, status: row.status as BuffetStatus, paymentStatus: row.payment_status, queueNumber: row.queue_number, createdAt: row.created_at, updatedAt: row.updated_at } }
const columns = 'id, user_id, name, phone, date, session, level, level_source, note, shuttle, amount, "group", status, payment_status, queue_number, created_at, updated_at'

export class D1BuffetRepository implements BuffetRepository {
  constructor(private readonly db: D1Database) {}
  async create(input: CreateBuffetBookingInput & { amount: number }): Promise<BuffetBooking> { const id = crypto.randomUUID(); const now = new Date().toISOString(); await this.db.prepare(`INSERT INTO buffet_bookings (${columns}) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`).bind(id, input.userId, input.name, input.phone, input.date, input.session, input.level ?? '', input.levelSource ?? 'self-assessed', input.note ?? '', input.shuttle ?? 0, input.amount, input.group ?? 'regular', 'pending', 'ไม่ชำระ', null, now, now).run(); return toBooking({ id, user_id: input.userId, name: input.name, phone: input.phone, date: input.date, session: input.session, level: input.level ?? '', level_source: input.levelSource ?? 'self-assessed', note: input.note ?? '', shuttle: input.shuttle ?? 0, amount: input.amount, group: input.group ?? 'regular', status: 'pending', payment_status: 'ไม่ชำระ', queue_number: null, created_at: now, updated_at: now }) }
  async findById(id: string): Promise<BuffetBooking | null> { const row = await this.db.prepare(`SELECT ${columns} FROM buffet_bookings WHERE id = ?`).bind(id).first<BuffetRow>(); return row ? toBooking(row) : null }
  async findByUser(userId: string): Promise<BuffetBooking[]> { const { results } = await this.db.prepare(`SELECT ${columns} FROM buffet_bookings WHERE user_id = ? ORDER BY created_at DESC`).bind(userId).all<BuffetRow>(); return results.map(toBooking) }
  async findBySchedule(date: string, session: string): Promise<BuffetBooking[]> { const { results } = await this.db.prepare(`SELECT ${columns} FROM buffet_bookings WHERE date = ? AND session = ? ORDER BY created_at`).bind(date, session).all<BuffetRow>(); return results.map(toBooking) }
  async updateStatus(id: string, status: BuffetStatus, updatedAt: string): Promise<BuffetBooking | null> { await this.db.prepare('UPDATE buffet_bookings SET status = ?, updated_at = ? WHERE id = ?').bind(status, updatedAt, id).run(); return this.findById(id) }
}
